### ISSUE TITLE
ModuleNotFoundError: No module named 'http.client'; 'http' is not a package

### ISSUE THREAD

**Issue by mdmomeni** [mediacloud/ultimate-sitemap-parser#28]
Code :
```python
from usp.tree import sitemap_tree_for_homepage
tree = sitemap_tree_for_homepage("https://www.nytimes.com/")
for page in tree.all_pages():
    print(page)
```
Error : 
```
Traceback (most recent call last):
  File "c:/Users/Raven/Desktop/CODE/GitHub/ezweb/src/ezweb/utils/sitemap.py", line 1, in <module>
    from usp.tree import sitemap_tree_for_homepage
  File "C:\Users\Raven\AppData\Local\Programs\Python\Python37\lib\site-packages\usp\tree.py", line 6, in <module>
    from .fetch_parse import SitemapFetcher
  File "C:\Users\Raven\AppData\Local\Programs\Python\Python37\lib\site-packages\usp\fetch_parse.py", line 11, in <module>
    from .helpers import (
  File "C:\Users\Raven\AppData\Local\Programs\Python\Python37\lib\site-packages\usp\helpers.py", line 15, in <module>
    from .web_client.abstract_client import (
  File "C:\Users\Raven\AppData\Local\Programs\Python\Python37\lib\site-packages\usp\web_client\abstract_client.py", line 4, in <module>
    from http import HTTPStatus
  File "c:\Users\Raven\Desktop\CODE\GitHub\ezweb\src\ezweb\utils\http.py", line 1, in <module>
    import requests
  File "C:\Users\Raven\AppData\Local\Programs\Python\Python37\lib\site-packages\requests\__init__.py", line 43, in <module>
    import urllib3
  File "C:\Users\Raven\AppData\Local\Programs\Python\Python37\lib\site-packages\urllib3\__init__.py", line 11, in <module>
    from . import exceptions
  File "C:\Users\Raven\AppData\Local\Programs\Python\Python37\lib\site-packages\urllib3\exceptions.py", line 3, in <module>
    from .packages.six.moves.http_client import IncompleteRead as httplib_IncompleteRead
  File "C:\Users\Raven\AppData\Local\Programs\Python\Python37\lib\site-packages\urllib3\packages\six.py", line 199, in load_module
    mod = mod._resolve()
  File "C:\Users\Raven\AppData\Local\Programs\Python\Python37\lib\site-packages\urllib3\packages\six.py", line 113, in _resolve
    return _import_module(self.mod)
  File "C:\Users\Raven\AppData\Local\Programs\Python\Python37\lib\site-packages\urllib3\packages\six.py", line 82, in _import_module
    __import__(name)
ModuleNotFoundError: No module named 'http.client'; 'http' is not a package
```

**Comment by mdmomeni** [comment]
I don't know why but when I put the program file outside of my package `ezweb.utils` it works fine . I think there was a conflict with used `request` libs in the other programs in my package
